#include <hpy.h>

// BEGIN: PointObject
typedef struct {
  long x;
  long y;
} PointObject;
HPyType_HELPERS(PointObject)
// END: PointObject

//// BEGIN: members
//HPyDef_MEMBER(Point_a, "a", HPyMember_SHORT, offsetof(PointObject, a))
//HPyDef_MEMBER(Point_b, "b", HPyMember_INT, offsetof(PointObject, b))
//HPyDef_MEMBER(Point_c, "c", HPyMember_LONG, offsetof(PointObject, c))
//HPyDef_MEMBER(Point_d, "d", HPyMember_FLOAT, offsetof(PointObject, d))
//HPyDef_MEMBER(Point_e, "e", HPyMember_DOUBLE, offsetof(PointObject, e))
//HPyDef_MEMBER(Point_f, "f", HPyMember_STRING, offsetof(PointObject, f))
//HPyDef_MEMBER(Point_g, "g", HPyMember_OBJECT, offsetof(PointObject, g))
//HPyDef_MEMBER(Point_h, "h", HPyMember_CHAR, offsetof(PointObject, h))
//HPyDef_MEMBER(Point_i, "i", HPyMember_BYTE, offsetof(PointObject, i))
//HPyDef_MEMBER(Point_j, "j", HPyMember_UBYTE, offsetof(PointObject, j))
//HPyDef_MEMBER(Point_k, "k", HPyMember_USHORT, offsetof(PointObject, k))
//HPyDef_MEMBER(Point_l, "l", HPyMember_UINT, offsetof(PointObject, l))
//HPyDef_MEMBER(Point_m, "m", HPyMember_ULONG, offsetof(PointObject, m))
//HPyDef_MEMBER(Point_n, "n", HPyMember_STRING_INPLACE, offsetof(PointObject, n))
//HPyDef_MEMBER(Point_o, "o", HPyMember_BOOL, offsetof(PointObject, o))
//HPyDef_MEMBER(Point_p, "p", HPyMember_OBJECT_EX, offsetof(PointObject, p))
//HPyDef_MEMBER(Point_q, "q", HPyMember_LONGLONG, offsetof(PointObject, q))
//HPyDef_MEMBER(Point_r, "r", HPyMember_ULONGLONG, offsetof(PointObject, r))
//HPyDef_MEMBER(Point_s, "s", HPyMember_HPYSSIZET, offsetof(PointObject, s))
//HPyDef_MEMBER(Point_t, "t", HPyMember_NONE, offsetof(PointObject, t))
//HPyDef_MEMBER(Point_u, "u", HPyMember_LONG, offsetof(PointObject, y))
// END: members
//    HPyMember_SHORT = 0,
//    HPyMember_INT = 1,
//    HPyMember_LONG = 2,
//    HPyMember_FLOAT = 3,
//    HPyMember_DOUBLE = 4,
//    HPyMember_STRING = 5,
//    HPyMember_OBJECT = 6,
//    HPyMember_CHAR = 7,   /* 1-character string */
//    HPyMember_BYTE = 8,   /* 8-bit signed int */
//    HPyMember_UBYTE = 9,
//    HPyMember_USHORT = 10,
//    HPyMember_UINT = 11,
//    HPyMember_ULONG = 12,
//    HPyMember_STRING_INPLACE = 13,
//    HPyMember_BOOL = 14,
//    HPyMember_OBJECT_EX = 16,  // Like T_OBJECT, but raises AttributeError
//    HPyMember_LONGLONG = 17,
//    HPyMember_ULONGLONG = 18,
//    HPyMember_HPYSSIZET = 19,  /* HPy_ssize_t */
//    HPyMember_NONE = 20,       /* Value is always None */

//// BEGIN: defines
//static HPyDef *Point_defines[] = {
//    &Point_x,
//    &Point_y,
//    NULL
//};
//// END: defines

//// BEGIN: spec
//static HPyType_Spec Point_spec = {
//    .name = "simple_type.Point",
//    .basicsize = sizeof(PointObject),
//    .builtin_shape = PointObject_SHAPE,
//    .defines = Point_defines
//};
//// END: spec

//// BEGIN: add_type
//HPyDef_SLOT(simple_exec, HPy_mod_exec)
//static int simple_exec_impl(HPyContext *ctx, HPy m) {
//    if (!HPyHelpers_AddType(ctx, m, "Point", &Point_spec, NULL)) {
//        return -1;
//    }
//    return 0; // success
//}

//static HPyDef *mod_defines[] = {
//    &simple_exec, // 'simple_exec' is generated by the HPyDef_SLOT macro
//    NULL,
//};

//static HPyModuleDef moduledef = {
//    .defines = mod_defines,
//    // ...
//// END: add_type
//    .doc = "A simple HPy type",
//};
//
//HPy_MODINIT(simple_type, moduledef)
