#include "hpy.h"


static HPy impl(HPyContext *ctx, HPy self)
{
    return HPyUnicode_FromString(ctx, "Hello world");
}

HPyFunc_TRAMPOLINE(say_hello_VARARGS, impl, HPyFunc_VARARGS);
HPyFunc_TRAMPOLINE(say_hello_KEYWORDS, impl, HPyFunc_KEYWORDS);
HPyFunc_TRAMPOLINE(say_hello_NOARGS, impl, HPyFunc_NOARGS);
HPyFunc_TRAMPOLINE(say_hello_O, impl, HPyFunc_O);
HPyFunc_TRAMPOLINE(say_hello_DESTROYFUNC, impl, HPyFunc_DESTROYFUNC);
HPyFunc_TRAMPOLINE(say_hello_GETBUFFERPROC, impl, HPyFunc_GETBUFFERPROC);
HPyFunc_TRAMPOLINE(say_hello_RELEASEBUFFERPROC, impl, HPyFunc_RELEASEBUFFERPROC);
HPyFunc_TRAMPOLINE(say_hello_UNARYFUNC, impl, HPyFunc_UNARYFUNC);
HPyFunc_TRAMPOLINE(say_hello_BINARYFUNC, impl, HPyFunc_BINARYFUNC);
HPyFunc_TRAMPOLINE(say_hello_TERNARYFUNC, impl, HPyFunc_TERNARYFUNC);
HPyFunc_TRAMPOLINE(say_hello_INQUIRY, impl, HPyFunc_INQUIRY);
HPyFunc_TRAMPOLINE(say_hello_LENFUNC, impl, HPyFunc_LENFUNC);
HPyFunc_TRAMPOLINE(say_hello_SSIZEARGFUNC, impl, HPyFunc_SSIZEARGFUNC);
HPyFunc_TRAMPOLINE(say_hello_SSIZESSIZEARGFUNC, impl, HPyFunc_SSIZESSIZEARGFUNC);
HPyFunc_TRAMPOLINE(say_hello_SSIZEOBJARGPROC, impl, HPyFunc_SSIZEOBJARGPROC);
HPyFunc_TRAMPOLINE(say_hello_SSIZESSIZEOBJARGPROC, impl, HPyFunc_SSIZESSIZEOBJARGPROC);
HPyFunc_TRAMPOLINE(say_hello_OBJOBJARGPROC, impl, HPyFunc_OBJOBJARGPROC);
HPyFunc_TRAMPOLINE(say_hello_FREEFUNC, impl, HPyFunc_FREEFUNC);
HPyFunc_TRAMPOLINE(say_hello_GETATTRFUNC, impl, HPyFunc_GETATTRFUNC);
HPyFunc_TRAMPOLINE(say_hello_GETATTROFUNC, impl, HPyFunc_GETATTROFUNC);
HPyFunc_TRAMPOLINE(say_hello_SETATTRFUNC, impl, HPyFunc_SETATTRFUNC);
HPyFunc_TRAMPOLINE(say_hello_SETATTROFUNC, impl, HPyFunc_SETATTROFUNC);
HPyFunc_TRAMPOLINE(say_hello_REPRFUNC, impl, HPyFunc_REPRFUNC);
HPyFunc_TRAMPOLINE(say_hello_HASHFUNC, impl, HPyFunc_HASHFUNC);
HPyFunc_TRAMPOLINE(say_hello_RICHCMPFUNC, impl, HPyFunc_RICHCMPFUNC);
HPyFunc_TRAMPOLINE(say_hello_GETITERFUNC, impl, HPyFunc_GETITERFUNC);
HPyFunc_TRAMPOLINE(say_hello_ITERNEXTFUNC, impl, HPyFunc_ITERNEXTFUNC);
HPyFunc_TRAMPOLINE(say_hello_DESCRGETFUNC, impl, HPyFunc_DESCRGETFUNC);
HPyFunc_TRAMPOLINE(say_hello_DESCRSETFUNC, impl, HPyFunc_DESCRSETFUNC);
HPyFunc_TRAMPOLINE(say_hello_INITPROC, impl, HPyFunc_INITPROC);
HPyFunc_TRAMPOLINE(say_hello_NEWFUNC, impl, HPyFunc_NEWFUNC);
HPyFunc_TRAMPOLINE(say_hello_GETTER, impl, HPyFunc_GETTER);
HPyFunc_TRAMPOLINE(say_hello_SETTER, impl, HPyFunc_SETTER);
HPyFunc_TRAMPOLINE(say_hello_OBJOBJPROC, impl, HPyFunc_OBJOBJPROC);
HPyFunc_TRAMPOLINE(say_hello_TRAVERSEPROC, impl, HPyFunc_TRAVERSEPROC);
HPyFunc_TRAMPOLINE(say_hello_DESTRUCTOR, impl, HPyFunc_DESTRUCTOR);
//HPyFunc_TRAMPOLINE(say_hello_CAPSULE_DESTRUCTOR, impl, HPyFunc_CAPSULE_DESTRUCTOR);
//HPyFunc_TRAMPOLINE(say_hello_VECTORCALLFUNC, impl, HPyFunc_VECTORCALLFUNC);
HPyFunc_TRAMPOLINE(say_hello_MOD_CREATE, impl, HPyFunc_MOD_CREATE);
